FITEM ftable[] = {
	{"eres",        1,TERMINAL},
        {"var",         3,TERMINAL},
	{"input",       1,TERMINAL},
	{"local",       1,TERMINAL},
	{"word",        1,TERMINAL},
	{"fcall",       4,TERMINAL},
	{"swchar",      1,TERMINAL},
	{"const",	1,CONST},
        {"nil",		1,SPL},
        {"cxfile",      4,CXFILE},
	{"scons",       3,	INTERIOR},
        {"wrd",         0,WRD},
        {"valof",       0,VALOF},
        {"decl",        0,DECL},
        {"defn",        0,DEFN},
        {"strg",        0,STRG},
        {"numb",        0,NMB},
        {"nullry",      0,NULLRY},
        {"nonnullry",   0,NONNULLRY},
        {"constant",    0,CONST},
	{"eglobal",     0,EGLOB},
	{"nglobal",     0,NGLOB},
	{"frmls",       0,FRMLS},
	{"op",          0,OP},
	{"first",	2,INTERIOR},
	{"next",	2,INTERIOR},
	{"pred",	2,INTERIOR},
	{"prev",	2,INTERIOR},
	{"fby", 	3,INTERIOR},
	{"before",	3,INTERIOR},
	{"asa",	        3,INTERIOR},
	{"now",		1,	INTERIOR},
	{"@t",		3,	INTERIOR},
	{"initial",	2,	INTERIOR},
	{"succ",	2,	INTERIOR},
	{"sby", 	3,	INTERIOR},
	{"whr", 	3,	INTERIOR},
	{"here", 	1,	INTERIOR},
	{"@s",		3,	INTERIOR},
	{"original",	2,	INTERIOR},
	{"noriginal",	2,	INTERIOR},
	{"nrest",	2,	INTERIOR},
	{"rest",	2,	INTERIOR},
	{"aby", 	3,	INTERIOR},
	{"cby", 	3,	INTERIOR},
	{"swap", 	3,	INTERIOR},
	{"rshift",	2,	INTERIOR},
	{"lshift",	2,	INTERIOR},
	{"all", 	2,	INTERIOR},
	{"elt",	        2,	INTERIOR},
	{"isnumber",	2,	INTERIOR},
	{"div",		3,	INTERIOR},
	{"mod",		3,	INTERIOR},
	{"and",		3,	INTERIOR},
	{"not",		2,	INTERIOR},
	{"or",		3,	INTERIOR},
	{"eq",		3,	INTERIOR},
	{"ne",		3,	INTERIOR},
	{"gt",		3,	INTERIOR},
	{"ge",		3,	INTERIOR},
	{"le",		3,	INTERIOR},
	{"lt",		3,	INTERIOR},
	{"sin",		2,	INTERIOR},
	{"cos",		2,	INTERIOR},
	{"log",		2,	INTERIOR},
	{"iseod",	2,	INTERIOR},
	{"isstring",	2,	INTERIOR},
	{"isword",	2,	INTERIOR},
	{"substr",	4,	INTERIOR},
	{"eod",		1,	SPL},
	{"arg",		2,	INTERIOR},
	{"mkword",	2,	INTERIOR},
	{"mkstring",	2,	INTERIOR},
	{"error",	1,	SPL},
	{"iserror",	2,	INTERIOR},
	{"length",	2,	INTERIOR},
	{"mknumber",	2,	INTERIOR},
	{"tan",		2,	INTERIOR},
	{"log10",	2,	INTERIOR},
	{"abs",		2,	INTERIOR},
	{"sqrt",	2,	INTERIOR},
	{"filter",	4,	INTERIOR},
        {"cons",	3,	INTERIOR}, 
        {"islist",	2,	INTERIOR},
        {"isatom",	2,	INTERIOR},
        {"hd",		2,	INTERIOR},
        {"tl",		2,	INTERIOR},
        {"ord",		2,	INTERIOR},
        {"chr",		2,	INTERIOR},
        {"isnil",	2,	INTERIOR},
        {"complex",	2,	INTERIOR},
        {"real",	2,	INTERIOR},
        {"imag",	2,	INTERIOR},
	{"uminus",      2,	INTERIOR},
	{"plus",        3,	INTERIOR},
	{"minus",       3,	INTERIOR},
	{"times",       3,	INTERIOR},
	{"if",          4,	INTERIOR},
	{"fdiv",        3,	INTERIOR},
	{"strconc",     3,	INTERIOR},
	{"append",      3,	INTERIOR},
	{"arg",         2,	INTERIOR},
	{"exp",         3,	INTERIOR},
        {"spl",         0,      INTERIOR},
};
